name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.0.0
      with:
        hugo-version: '0.58.2'

    - name: Clone theme
      run: cd blog/themes && git clone https://github.com/olOwOlo/hugo-theme-even && cd hugo-theme-even && git reset --hard d39d3e443953caea05510b19fdd7a259c71a0ab3

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir -s blog -d public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./blog/public
